l_simp_chinese:

custom_diff_strong_MOT:0 "加强蒙德"
custom_diff_strong_LYY:0 "加强璃月"
custom_diff_strong_INA:0 "加强稻妻"
custom_diff_strong_SUM:0 "加强须弥"
custom_diff_strong_FON:0 "加强枫丹"
custom_diff_strong_NAT:0 "加强纳塔"
custom_diff_strong_SNE:0 "加强至冬"
custom_diff_strong_ABY:0 "加强深渊"
custom_diff_strong_PRI:0 "加强天理"
custom_diff_strong_Mysterious_forces:0 "加强彩蛋国家"



