l_english:


custom_diff_strong_MOT:0 "Strengthening Mondstadt"
custom_diff_strong_LYY:0 "Strengthening Liyue"
custom_diff_strong_INA:0 "Strengthening Inazuma"
custom_diff_strong_SUM:0 "Strengthening Sumeru"
custom_diff_strong_FON:0 "Strengthening Fontaine"
custom_diff_strong_NAT:0 "Strengthening Natlan"
custom_diff_strong_SNE:0 "Strengthening Snezhnaya"
custom_diff_strong_ABY:0 "Strengthening Abyss"
custom_diff_strong_PRI:0 "Strengthening Principle"
custom_diff_strong_Mysterious_forces:0 "Strengthening Mysterious Forces"


